version: '3.8'

services:
  url-shortener:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_PASSWORD=password

  database:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/posgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5436:5432
    