version: '3.8'

networks:
  dev: 

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - url-shortener  

  url-shortener:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_PASSWORD=password
    networks:
      - dev

  database:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/posgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5436:5432 